### ISSUE TITLE
Use relative URIs for sub-resources

### ISSUE THREAD

**Issue by leftmostcat** [bookbrainz/bookbrainz-ws#18]
Instead of providing absolute URIs for all resources, we should use relative URIs to simplify processing by the frontend. For now, we'll provide a configuration option to allow enabling absolute URLs.

**Comment by LordSputnik** [comment]
Decided against this for 0.15.3, because it would result in URLs looking like "/ws/...", while the models would probably expect just "/...".

**Comment by LordSputnik** [comment]
Decided to go with relative here: http://chatlogs.musicbrainz.org/bookbrainz-devel/2015/2015-04/2015-04-06.html#T21-56-36-373691

I suggest we handle this in June with the ws/data/schema re-organisation, though.

**Comment by LordSputnik** [comment]
http://tickets.musicbrainz.org/browse/BB-72

**Comment by LordSputnik** [comment]
Closing - moved to JIRA.
